### ISSUE TITLE
Extending Dynamic Navigation Links

### ISSUE THREAD

**Issue by johnkattenhorn** [Useful-Software-Solutions-Ltd/Angular.Net.SecureStarter#1]
This template was a big help in getting me started with AngularJS, I was wondering if you had any suggestions for me to extend the navigation service to allow related links to be shown as a dropdown ?

**Comment by JayChase** [comment]
Sorry it's taken me so long to get back to you. I've been trying out an approach to handle nested nav links . I've put a demo up on Plunkr http://plnkr.co/XNAHZU it seems to work OK. With regard to the ADAL work that sounds really good. Maybe it would be best as a fork for now. Then if it looks like there is a way of getting it into the main branch as a configurable option that could work too.
