### ISSUE TITLE
External login

### ISSUE THREAD

**Issue by SkyQuant** [Useful-Software-Solutions-Ltd/Angular.Net.SecureStarter#4]
Trying to login with Facebook I have never ending message  ```checking email...```

**Comment by JayChase** [comment]
Hi. Did you resolve this issue? If not I'll test for it and get a fix in the next version.

**Comment by SkyQuant** [comment]
Hi Jay. Please, check this problem. Urgently need.

**Comment by juntaforce** [comment]
Are there any sample as like google external login  for Facebook?? how can  I get email ??

**Comment by JayChase** [comment]
Hi. There is a walkthrough for external logins in the wiki https://github.com/Useful-Software-Solutions-Ltd/Angular.Net.SecureStarter/wiki/Setting-up-an-external-authentication-provider. To be honest this project has fallen a bit out of date, I'm waiting for ASP.NET 5 to be released before taking a decision on what to do about a new version.

**Comment by juntaforce** [comment]
Hi Jack, Thanks for your info. But There is no ending with this.. After ASP.NET5 release,  Angular release new version 2.0.0 than everything have to change :)
For this reason,I would like to continue with your project and I have one more question.
Is it possible to seperate two project with api and Angular spa ?? If its possible, which part have to be change on angular spa side as URL(I mean baseurl or apiurl) to reach to web api ??

**Comment by JayChase** [comment]
Hi, you are right you can change the baseUrl in accountClientSvc to point to a separate auth server.
